"""
briefkit.templates.report
~~~~~~~~~~~~~~~~~~~~~~~~~
Formal report template.

Build order:
  Cover → TOC → Abstract → Methodology → Findings (body) →
  Discussion → Recommendations → Appendices → Bibliography → Back Cover

Key differences from BriefingTemplate:
  - Abstract replaces Executive Summary (250-word max, formal register)
  - Methodology section auto-populated from content or methodology.md
  - Recommendations auto-extracted (bold "recommend" keywords)
  - No dashboard, no classification banner
  - No back cover branding bar — just colophon line
"""

from __future__ import annotations

import re
from pathlib import Path

from reportlab.platypus import Paragraph, Spacer, PageBreak, KeepTogether
from reportlab.lib.units import mm

from briefkit.generator import (
    BaseBriefingTemplate,
    build_callout_box,
    build_cover_page,
    build_data_table,
    build_toc,
)
from briefkit.styles import _safe_para, _ps, _hex
from briefkit.extractor import parse_markdown


class ReportTemplate(BaseBriefingTemplate):
    """
    Formal report template.

    Produces a structured report suitable for academic or professional
    submission: abstract, methodology, findings, discussion,
    recommendations, appendices.
    """

    def build_story(self, content: dict) -> list:
        """
        Assemble the report story:
        Cover, TOC, Abstract, Methodology, Findings, Discussion,
        Recommendations, Appendices, Bibliography, Colophon.
        """
        story = []

        # Cover
        story.extend(build_cover_page(
            title    = content.get("title", self.target_path.name.replace("-", " ").title()),
            subtitle = "Formal Report",
            path     = str(self.target_path),
            level    = self.level,
            date     = self.date,
            doc_id   = self.doc_id,
            brand    = self.brand,
            content_width = self.content_width,
        ))

        # Pre-build optional sections to drive dynamic TOC
        source_type       = content.get("metrics", {}).get("source_type", "ACADEMIC")
        bib_flowables     = self.build_bibliography(
            content.get("bibliography", []), source_type=source_type
        )

        abstract_flowables     = self._build_abstract(content)
        methodology_flowables  = self._build_methodology(content)
        findings_flowables     = self._build_findings(content)
        discussion_flowables   = self._build_discussion(content)
        recommend_flowables    = self._build_recommendations(content)
        appendix_flowables     = self._build_appendices(content)

        # TOC
        story.append(_safe_para("Table of Contents", self.styles["STYLE_H1"]))
        story.append(Spacer(1, 2 * mm))

        toc_entries = [(1, "Abstract")]
        if methodology_flowables:
            toc_entries.append((1, "Methodology"))
        toc_entries.append((1, "Findings"))
        for i, sub in enumerate(content.get("subsystems", []), 1):
            toc_entries.append((2, f"  {i}. {sub.get('name', f'Section {i}')}"))
        toc_entries.append((1, "Discussion"))
        if recommend_flowables:
            toc_entries.append((1, "Recommendations"))
        if appendix_flowables:
            toc_entries.append((1, "Appendices"))
        if bib_flowables:
            toc_entries.append((1, "References"))

        story.extend(build_toc(toc_entries, brand=self.brand, content_width=self.content_width))
        story.append(PageBreak())

        # Sections
        story.extend(abstract_flowables)
        story.append(PageBreak())

        if methodology_flowables:
            story.extend(methodology_flowables)
            story.append(PageBreak())

        story.extend(findings_flowables)
        story.append(PageBreak())

        story.extend(discussion_flowables)
        story.append(PageBreak())

        if recommend_flowables:
            story.extend(recommend_flowables)
            story.append(PageBreak())

        if appendix_flowables:
            story.extend(appendix_flowables)
            story.append(PageBreak())

        if bib_flowables:
            story.extend(bib_flowables)

        # Colophon (no back cover page)
        story.append(Spacer(1, 20 * mm))
        colophon_style = _ps(
            "ReportColophon", brand=self.brand,
            fontSize=8, textColor=_hex(self.brand, "caption"), alignment=1,
        )
        story.append(Paragraph(
            f"Generated by briefkit on {self.date_str}.",
            colophon_style,
        ))

        return story

    # ------------------------------------------------------------------
    # Abstract
    # ------------------------------------------------------------------

    def _build_abstract(self, content: dict) -> list:
        """
        Build a 250-word-max abstract from the overview and key findings.
        """
        flowables = []
        flowables.append(Paragraph("Abstract", self.styles["STYLE_H1"]))
        flowables.append(Spacer(1, 2 * mm))

        overview   = content.get("overview", "")
        orientation = content.get("orientation", "")
        title      = content.get("title", "this study")
        subsystems = content.get("subsystems", [])

        # Derive a formal abstract text
        # Strategy: overview first paragraph + key findings summary
        abstract_parts: list[str] = []

        # First non-trivial paragraph from overview
        if overview:
            paragraphs = [p.strip() for p in re.split(r'\n\n+', overview) if p.strip()]
            for para in paragraphs[:2]:
                clean = re.sub(r'#+ ', '', para).strip()
                if len(clean) > 50:
                    abstract_parts.append(clean)
                    break

        # Orientation "what is" text as fallback
        if not abstract_parts and orientation:
            m = re.search(r'^(?!#)(.{60,})', orientation, re.MULTILINE)
            if m:
                abstract_parts.append(m.group(1).strip())

        # Extract one key finding per subsystem (first meaningful sentence)
        findings: list[str] = []
        for sub in subsystems[:4]:
            raw = sub.get("content", "").replace("\n", " ")
            for s in re.split(r'(?<=[.!?])\s+', raw):
                s = s.strip().lstrip("#- *>`|")
                if len(s) > 40 and not s.startswith("```"):
                    findings.append(s[:150])
                    break

        if findings:
            abstract_parts.append(
                "Key findings include: " + "; ".join(findings[:3]) + "."
            )

        if not abstract_parts:
            abstract_parts.append(
                f"This report presents findings on {title}, "
                f"covering {len(subsystems)} major section(s). "
                f"See the Findings section for detailed analysis."
            )

        # Join and truncate to ~250 words
        full_abstract = " ".join(abstract_parts)
        words = full_abstract.split()
        if len(words) > 250:
            full_abstract = " ".join(words[:250]) + "\u2026"

        flowables.append(Paragraph(full_abstract, self.styles["STYLE_BODY"]))

        # Keywords derived from terms
        terms = list(content.get("terms", {}).keys())[:8]
        if terms:
            flowables.append(Spacer(1, 2 * mm))
            kw_style = _ps(
                "AbstractKeywords", brand=self.brand,
                fontSize=9, textColor=_hex(self.brand, "caption"),
                fontName="Helvetica-Oblique",
            )
            flowables.append(Paragraph(
                "<b>Keywords:</b> " + ", ".join(terms),
                kw_style,
            ))

        return flowables

    # ------------------------------------------------------------------
    # Methodology
    # ------------------------------------------------------------------

    def _build_methodology(self, content: dict) -> list:
        """
        Build the methodology section.

        Sources (in order of preference):
          1. methodology.md file in target directory
          2. methodology.md in any subdirectory
          3. Auto-synthesized from source type and doc structure
        """
        # Search for methodology.md
        method_path = self.target_path / "methodology.md"
        if not method_path.exists():
            candidates = list(self.target_path.rglob("methodology.md"))
            method_path = candidates[0] if candidates else None

        flowables = []
        flowables.append(Paragraph("Methodology", self.styles["STYLE_H1"]))
        flowables.append(Spacer(1, 2 * mm))

        if method_path and method_path.exists():
            raw = method_path.read_text(encoding="utf-8", errors="replace")
            for block in parse_markdown(raw)[:40]:
                flowables.extend(self.render_blocks([block]))
        else:
            # Auto-synthesize from source type and structure
            source_type = content.get("metrics", {}).get("source_type", "ACADEMIC")
            subsystems  = content.get("subsystems", [])
            doc_count   = content.get("metrics", {}).get("doc_count", len(subsystems))

            if source_type == "ACADEMIC":
                method_text = (
                    f"This report synthesizes {doc_count} source document(s) using a "
                    "systematic literature review approach. Content was extracted from "
                    "primary source materials, structured into thematic sections, and "
                    "analysed for key findings, data tables, and cross-references."
                )
            elif source_type in ("MANUFACTURER", "DOCUMENTATION"):
                method_text = (
                    f"This report was compiled from {doc_count} technical document(s) "
                    "using structured content extraction. Procedures, specifications, and "
                    "reference data were identified and organized by subsystem."
                )
            else:
                method_text = (
                    f"Content for this report was drawn from {doc_count} source document(s). "
                    "Material was organized thematically with citations preserved from the "
                    "original sources."
                )

            flowables.append(Paragraph(method_text, self.styles["STYLE_BODY"]))

            if subsystems:
                flowables.append(Spacer(1, 1.5 * mm))
                flowables.append(Paragraph("Source Sections Analysed", self.styles["STYLE_H2"]))
                for i, sub in enumerate(subsystems, 1):
                    flowables.append(_safe_para(
                        f"\u2022 {sub['name']}",
                        _ps("MethodList", brand=self.brand, fontSize=10,
                            textColor=_hex(self.brand, "body_text"), leading=14, leftIndent=12),
                    ))

        return flowables

    # ------------------------------------------------------------------
    # Findings
    # ------------------------------------------------------------------

    def _build_findings(self, content: dict) -> list:
        """
        Build the Findings section — one H2 per subsystem, full content.
        """
        flowables = []
        flowables.append(Paragraph("Findings", self.styles["STYLE_H1"]))
        flowables.append(Spacer(1, 2 * mm))
        flowables.append(Paragraph(
            "Findings are presented per section as extracted from the source material.",
            self.styles["STYLE_BODY"],
        ))
        flowables.append(Spacer(1, 2 * mm))

        subsystems = content.get("subsystems", [])
        if not subsystems:
            overview = content.get("overview", "No findings available.")
            flowables.append(Paragraph(overview[:2000], self.styles["STYLE_BODY"]))
            return flowables

        for idx, sub in enumerate(subsystems, start=1):
            flowables.append(Paragraph(f"{idx}. {sub['name']}", self.styles["STYLE_H2"]))
            flowables.append(Spacer(1, 1.5 * mm))

            blocks = sub.get("blocks") or parse_markdown(sub.get("content", ""))
            rendered = 0
            for block in blocks:
                if block["type"] == "heading" and block["level"] <= 2:
                    continue
                for fl in self.render_blocks([block]):
                    flowables.append(fl)
                    rendered += 1
                    if rendered >= 80:
                        break
                if rendered >= 80:
                    break

            flowables.append(Spacer(1, 2 * mm))

        return flowables

    # ------------------------------------------------------------------
    # Discussion
    # ------------------------------------------------------------------

    def _build_discussion(self, content: dict) -> list:
        """
        Build a discussion section synthesizing key themes from the findings.
        """
        flowables = []
        flowables.append(Paragraph("Discussion", self.styles["STYLE_H1"]))
        flowables.append(Spacer(1, 2 * mm))

        title = content.get("title", "the subject")
        subsystems = content.get("subsystems", [])

        flowables.append(Paragraph(
            f"The findings presented in this report illuminate several important dimensions "
            f"of {title}. The following discussion draws cross-cutting observations from "
            f"the {len(subsystems)} section(s) analysed.",
            self.styles["STYLE_BODY"],
        ))
        flowables.append(Spacer(1, 2 * mm))

        # Extract blockquote insights across all subsystems as discussion points
        insights: list[str] = []
        for sub in subsystems:
            for insight in sub.get("insights", []):
                if len(insight) > 30:
                    insights.append((sub["name"], insight))

        if insights:
            flowables.append(Paragraph("Key Observations", self.styles["STYLE_H2"]))
            flowables.append(Spacer(1, 1.5 * mm))
            for name, text in insights[:6]:
                flowables.append(build_callout_box(
                    f"From {name}: {text[:300]}", "insight", brand=self.brand, content_width=self.content_width
                ))

        # All-table summary for cross-section comparisons
        all_tables = []
        for sub in subsystems:
            for tbl in sub.get("tables", []):
                if tbl.get("headers") and len(tbl.get("rows", [])) > 0:
                    all_tables.append((sub["name"], tbl))

        if all_tables:
            flowables.append(Spacer(1, 2 * mm))
            flowables.append(Paragraph("Data Summary", self.styles["STYLE_H2"]))
            flowables.append(Spacer(1, 1.5 * mm))
            for name, tbl in all_tables[:3]:
                flowables.append(Paragraph(name, self.styles["STYLE_H3"]))
                flowables.extend(build_data_table(
                    tbl["headers"], tbl["rows"], brand=self.brand, content_width=self.content_width
                ))
                flowables.append(Spacer(1, 1.5 * mm))

        return flowables

    # ------------------------------------------------------------------
    # Recommendations
    # ------------------------------------------------------------------

    def _build_recommendations(self, content: dict) -> list:
        """
        Auto-extract recommendations from bold "recommend" keywords in content.

        Pattern: sentences containing "recommend", "should", "must", or "propose"
        within bold-formatted runs or standalone sentences.
        """
        rec_pattern = re.compile(
            r'(?:^|\.\s+|\n)([^.\n]*?\b(?:recommend|should\s+be|must\s+be|propose|suggest|advise)\b[^.\n]*\.)',
            re.IGNORECASE | re.MULTILINE,
        )

        recommendations: list[str] = []
        for sub in content.get("subsystems", []):
            raw = sub.get("content", "")
            for m in rec_pattern.finditer(raw):
                rec = m.group(1).strip()
                if 20 < len(rec) < 300:
                    recommendations.append((sub["name"], rec))
            if len(recommendations) >= 10:
                break

        # Also scan overview
        for m in rec_pattern.finditer(content.get("overview", "")):
            rec = m.group(1).strip()
            if 20 < len(rec) < 300:
                recommendations.append(("Overview", rec))

        if not recommendations:
            return []

        flowables = []
        flowables.append(Paragraph("Recommendations", self.styles["STYLE_H1"]))
        flowables.append(Spacer(1, 2 * mm))
        flowables.append(Paragraph(
            "The following recommendations are drawn directly from the source material.",
            self.styles["STYLE_BODY"],
        ))
        flowables.append(Spacer(1, 2 * mm))

        for i, (section_name, text) in enumerate(recommendations[:12], 1):
            flowables.append(Paragraph(
                f"{i}. {text}",
                _ps(f"Rec_{i}", brand=self.brand,
                    fontSize=10, textColor=_hex(self.brand, "body_text"),
                    leading=14, leftIndent=12, spaceBefore=4, spaceAfter=2),
            ))
            flowables.append(_safe_para(
                f"<i>Source: {section_name}</i>",
                _ps(f"RecSource_{i}", brand=self.brand,
                    fontSize=8, textColor=_hex(self.brand, "caption"),
                    fontName="Helvetica-Oblique", leftIndent=12, spaceAfter=4),
            ))

        return flowables

    # ------------------------------------------------------------------
    # Appendices
    # ------------------------------------------------------------------

    def _build_appendices(self, content: dict) -> list:
        """
        Build appendices from any files named appendix*.md or appendices.md
        in the target directory.  Falls back to brilliance_summary.
        """
        appendix_files = sorted(
            list(self.target_path.glob("appendix*.md"))
            + list(self.target_path.glob("appendices.md"))
        )

        brilliance = content.get("brilliance_summary", "")

        if not appendix_files and not brilliance:
            return []

        flowables = []
        flowables.append(Paragraph("Appendices", self.styles["STYLE_H1"]))
        flowables.append(Spacer(1, 2 * mm))

        if appendix_files:
            for i, fp in enumerate(appendix_files, 1):
                raw = fp.read_text(encoding="utf-8", errors="replace")
                label = fp.stem.replace("-", " ").title()
                flowables.append(Paragraph(f"Appendix {chr(64+i)}: {label}", self.styles["STYLE_H2"]))
                flowables.append(Spacer(1, 1.5 * mm))
                for block in parse_markdown(raw)[:40]:
                    flowables.extend(self.render_blocks([block]))
                flowables.append(Spacer(1, 2 * mm))
        elif brilliance:
            flowables.append(Paragraph("Appendix A: Engineering Brilliance", self.styles["STYLE_H2"]))
            flowables.append(Spacer(1, 1.5 * mm))
            for block in parse_markdown(brilliance)[:30]:
                flowables.extend(self.render_blocks([block]))

        return flowables

    # ------------------------------------------------------------------
    # Override unused base methods to no-ops
    # ------------------------------------------------------------------

    def build_at_a_glance(self, *args, **kwargs) -> list:
        return []

    def build_executive_summary(self, *args, **kwargs) -> list:
        return []
